- name: Enable both .ssh/authorized_keys and .ssh/authorized_keys2
  hosts: targets
  become: yes

  tasks:
          - name: Comment out authorizedKeysFile .ssh/authorized_keys
            replace:
                    path: /etc/ssh/sshd_config
                    regexp: '^AuthorizedKeysFile .ssh/authorized_keys'
                    replace: '#AuthorizedKeysFile .ssh/authorized_keys'
                    #                    regexp: '(\s+)AuthorizedKeysFile .ssh/authorized_keys'
                    #                    replace: '\n\t#AuthorizedKeysFile .ssh/authorized_keys'
                    backup: yes
          - name: Restart sshd
            service:
                    name: sshd
                    state: restarted

