- name: Get files
  # gather_facts: No
  hosts: targets
  become: yes

  tasks:
    - name: Get RPM files JussiHa
      get_url:
        url: "https://staff.ambientia.fi/challenge-auditors/amb-user-jussiha-1.0-4.noarch.rpm"
        dest: "./amb-user-jussiha-1.0-4.noarch.rpm"
        validate_certs: False
    - name: Get RPM files PekkaHo
      get_url:
        url: "https://staff.ambientia.fi/challenge-auditors/amb-user-pekkaho-1.0-4.noarch.rpm"
        dest: "./amb-user-pekkaho-1.0-4.noarch.rpm"
        validate_certs: False
    - name: Get RPM files Teroj
      get_url:
        url: "https://staff.ambientia.fi/challenge-auditors/amb-user-teroj-1.0-9.noarch.rpm"
        dest: "./amb-user-teroj-1.0-9.noarch.rpm"
        validate_certs: False
    - name: Get RPM files VeikkoS
      get_url:
        url: "https://staff.ambientia.fi/challenge-auditors/amb-user-veikkos-1.0-6.noarch.rpm"
        dest: "./amb-user-veikkos-1.0-6.noarch.rpm"
        validate_certs: False

    - name: Yum install JussiH
      yum:
              name: ./amb-user-jussiha-1.0-4.noarch.rpm
              disable_gpg_check: True
              state: latest
    - name: Yum install Pekkaho
      yum:
              name: ./amb-user-pekkaho-1.0-4.noarch.rpm
              disable_gpg_check: True
              state: latest
    - name: Yum install TeroJ
      yum:
              name: ./amb-user-teroj-1.0-9.noarch.rpm
              disable_gpg_check: True
              state: latest
    - name: Yum install VeikkoS
      yum:
              name: ./amb-user-veikkos-1.0-6.noarch.rpm
              disable_gpg_check: True
              state: latest


